services:
  - type: web
    name: zenverse-app
    env: node
    plan: free
    buildCommand: chmod +x build-optimized.sh && ./build-optimized.sh
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max-old-space-size=2048
      - key: GENERATE_SOURCEMAP
        value: false
      - key: CI
        value: false
      - key: SKIP_PREFLIGHT_CHECK
        value: true
      - key: NPM_CONFIG_CACHE
        value: /tmp/.npm
      - key: NPM_CONFIG_PREFER_OFFLINE
        value: true
