services:
  - type: web
    name: zenverse-app
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max-old-space-size=4096
      - key: GENERATE_SOURCEMAP
        value: false
      - key: CI
        value: false
